version: '3.1'
services:

  jenkinmaster:
    image: jenkin-master
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mynetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000   # outsite containner port : connterport 
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false

volumes:
  jenkins_home:

networks:
  mynetwork:
